POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNzcwNTg5ODAzLCJ1c2VySWQiOjF9.ISfiI0jFM-uYwDsFz3s-TJ4_N4x9vqLe70DKfRSijF8

{
    "title": "Test event",
    "description": "Test description",
    "location": "Test location",
    "datetime": "2025-01-01T15:30:00.000Z"
}